// Code generated by MockGen. DO NOT EDIT.
// Source: jwtUsecase.go
//
// Generated by this command:
//
//	mockgen -source=jwtUsecase.go -destination=../../../mock/mock_jwt_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	gomock "go.uber.org/mock/gomock"
)

// MockJWTUsecase is a mock of JWTUsecase interface.
type MockJWTUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockJWTUsecaseMockRecorder
	isgomock struct{}
}

// MockJWTUsecaseMockRecorder is the mock recorder for MockJWTUsecase.
type MockJWTUsecaseMockRecorder struct {
	mock *MockJWTUsecase
}

// NewMockJWTUsecase creates a new mock instance.
func NewMockJWTUsecase(ctrl *gomock.Controller) *MockJWTUsecase {
	mock := &MockJWTUsecase{ctrl: ctrl}
	mock.recorder = &MockJWTUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTUsecase) EXPECT() *MockJWTUsecaseMockRecorder {
	return m.recorder
}
