// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCockroachHandler creates a new instance of MockCockroachHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCockroachHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCockroachHandler {
	mock := &MockCockroachHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCockroachHandler is an autogenerated mock type for the CockroachHandler type
type MockCockroachHandler struct {
	mock.Mock
}

type MockCockroachHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCockroachHandler) EXPECT() *MockCockroachHandler_Expecter {
	return &MockCockroachHandler_Expecter{mock: &_m.Mock}
}

// DetectCockroach provides a mock function for the type MockCockroachHandler
func (_mock *MockCockroachHandler) DetectCockroach(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockCockroachHandler_DetectCockroach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectCockroach'
type MockCockroachHandler_DetectCockroach_Call struct {
	*mock.Call
}

// DetectCockroach is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockCockroachHandler_Expecter) DetectCockroach(c interface{}) *MockCockroachHandler_DetectCockroach_Call {
	return &MockCockroachHandler_DetectCockroach_Call{Call: _e.mock.On("DetectCockroach", c)}
}

func (_c *MockCockroachHandler_DetectCockroach_Call) Run(run func(c *gin.Context)) *MockCockroachHandler_DetectCockroach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCockroachHandler_DetectCockroach_Call) Return() *MockCockroachHandler_DetectCockroach_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCockroachHandler_DetectCockroach_Call) RunAndReturn(run func(c *gin.Context)) *MockCockroachHandler_DetectCockroach_Call {
	_c.Run(run)
	return _c
}
