// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Username  *string            `json:"username"`
	Password  *string            `json:"password"`
	Email     *string            `json:"email"`
	Role      string             `json:"role"`
	Active    bool               `json:"active"`
}

type AuthMethod struct {
	ID                string             `json:"id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	AuthID            *string            `json:"auth_id"`
	Provider          string             `json:"provider"`
	ProviderID        string             `json:"provider_id"`
	Email             *string            `json:"email"`
	UserID            *string            `json:"user_id"`
	Name              *string            `json:"name"`
	FirstName         *string            `json:"first_name"`
	LastName          *string            `json:"last_name"`
	NickName          *string            `json:"nick_name"`
	Description       *string            `json:"description"`
	AvatarUrl         *string            `json:"avatar_url"`
	Location          *string            `json:"location"`
	AccessToken       *string            `json:"access_token"`
	RefreshToken      *string            `json:"refresh_token"`
	IDToken           *string            `json:"id_token"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AccessTokenSecret *string            `json:"access_token_secret"`
}

type Cockroach struct {
	ID        int32              `json:"id"`
	Amount    int32              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
