// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"template-golang/config"
	"template-golang/modules/cockroach/handlers"
)

// Injectors from wire.go:

func Wire(conf *config.Config, cockroachH handlers.CockroachHandler) (Server, error) {
	serverGinServer := NewGinServer(conf, cockroachH)
	return serverGinServer, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	NewGinServer, wire.Bind(new(Server), new(*ginServer)),
)
