// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package database

import (
	"github.com/google/wire"
	"template-golang/config"
)

// Injectors from wire.go:

func WirePostgres(conf *config.Config) (Database, error) {
	databasePostgresDatabase := NewPostgres(conf)
	return databasePostgresDatabase, nil
}

// wire.go:

var PostgresProviderSet = wire.NewSet(
	NewPostgres, wire.Bind(new(Database), new(*postgresDatabase)),
)
