// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func Wire() (*Config, error) {
	configOption := RootConfig()
	config := Provide(configOption)
	return config, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	RootConfig,
	Provide,
)

func RootConfig() *ConfigOption {
	return NewConfigOption(".")
}
