// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/google/wire"
	"template-golang/database"
	"template-golang/modules/auth/middlewares"
)

// Injectors from wire.go:

func Wire(db database.Database) (*Auth, error) {
	userAuthMiddleware := middlewares.Provide()
	auth := &Auth{
		Handler: userAuthMiddleware,
	}
	return auth, nil
}

// wire.go:

var ProviderSet = wire.NewSet(middlewares.ProviderSet, wire.Struct(new(Auth), "*"))
