// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repositories

import (
	"github.com/google/wire"
	"template-golang/database"
)

// Injectors from wire.go:

func Wire(db database.Database) (CockroachMessaging, error) {
	repositoriesCockroachFCMMessaging := NewCockroachFCMMessaging()
	return repositoriesCockroachFCMMessaging, nil
}

// wire.go:

var RepositorySet = wire.NewSet(
	NewCockroachFCMMessaging, wire.Bind(new(CockroachMessaging), new(*cockroachFCMMessaging)),
)
