// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockServer
func (_mock *MockServer) Start() {
	_mock.Called()
	return
}

// MockServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockServer_Expecter) Start() *MockServer_Start_Call {
	return &MockServer_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockServer_Start_Call) Run(run func()) *MockServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServer_Start_Call) Return() *MockServer_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_Start_Call) RunAndReturn(run func()) *MockServer_Start_Call {
	_c.Run(run)
	return _c
}
