// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package userauth

import (
	"github.com/google/wire"
	"template-golang/database"
	"template-golang/modules/userauth/middlewares"
)

// Injectors from wire.go:

func Wire(db database.Database) (*UserAuth, error) {
	userAuthMiddleware := middlewares.Provide()
	userAuth := &UserAuth{
		Handler: userAuthMiddleware,
	}
	return userAuth, nil
}

// wire.go:

var ProviderSet = wire.NewSet(middlewares.ProviderSet, wire.Struct(new(UserAuth), "*"))
