// // Code generated by Wire. DO NOT EDIT.

// //go:generate go run -mod=mod github.com/google/wire/cmd/wire
// //go:build !wireinject
// // +build !wireinject

// package usecases

// import (
// 	"github.com/google/wire"
// 	"template-golang/config"
// )

// // Injectors from wire.go:

// func Wire(conf *config.Config) (Database, error) {
// 	databasePostgresDatabase := NewPostgresDatabase(conf)
// 	return databasePostgresDatabase, nil
// }

// // wire.go:

// var DatabaseSet = wire.NewSet(
// 	NewPostgresDatabase, wire.Bind(new(Database), new(*postgresDatabase)),
// )

// FIXME: after done other wire uncomment this