// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cockroach

import (
	"github.com/google/wire"
	"template-golang/database"
	"template-golang/modules/cockroach/handlers"
	"template-golang/modules/cockroach/repositories"
	"template-golang/modules/cockroach/usecases"
)

// Injectors from wire.go:

func Wire(db database.Database) (*Cockroach, error) {
	cockroachPostgresRepository := repositories.NewCockroachPostgresRepository(db)
	cockroachFCMMessaging := repositories.NewCockroachFCMMessaging()
	cockroachUsecaseImpl := usecases.NewCockroachUsecaseImpl(cockroachPostgresRepository, cockroachFCMMessaging)
	cockroachHttpHandler := handlers.NewCockroachHttpHandler(cockroachUsecaseImpl)
	cockroach := &Cockroach{
		Handler:    cockroachHttpHandler,
		Repository: cockroachPostgresRepository,
		Messaging:  cockroachFCMMessaging,
		Usecase:    cockroachUsecaseImpl,
	}
	return cockroach, nil
}

// wire.go:

var ProviderSet = wire.NewSet(handlers.ProviderSet, repositories.ProviderSet, usecases.ProviderSet, wire.Struct(new(Cockroach), "*"))
